In [1]:
from __future__ import division
import itertools
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import numpy as np
import pandas as pd
import math
from sklearn import metrics
from random import randint
from matplotlib import style
import seaborn as sns
%matplotlib inline

import bs4 as bs
import urllib.request
import csv
import pandas as pd
import time

In [2]:
colnames=['ip', 'timestamp', 'request_method', 'status', 'size',
          'destination', 'request_agent']
df_orig = pd.read_csv('http://python.zach.lol/access.log',          
                 engine='python',
                 header=None,
                 index_col=False,
                 names=colnames,
                 sep=r'\s(?=(?:[^"]*"[^"]*")*[^"]*$)(?![^\[]*\])',
                 na_values='"-"',
                 usecols=[0, 3, 4, 5, 6, 7, 8])

In [3]:
df_orig.head(2)

,ip,timestamp,request_method,status,size,destination,request_agent
0,97.105.19.58,[16/Apr/2019:19:34:42 +0000],"""GET /api/v1/sales?page=81 HTTP/1.1""",200,512495,NaN,"""python-requests/2.21.0"""
1,97.105.19.58,[16/Apr/2019:19:34:42 +0000],"""GET /api/v1/items HTTP/1.1""",200,3561,NaN,"""python-requests/2.21.0"""

In [4]:
new = pd.DataFrame([["95.31.18.119", "[21/Apr/2019:10:02:41+0000]", 
                     "GET /api/v1/items/HTTP/1.1", 200, 1153005, np.nan, 
                     "python-requests/2.21.0"],
                    ["95.31.16.121", "[17/Apr/2019:19:36:41+0000]", 
                     "GET /api/v1/sales?page=79/HTTP/1.1", 301, 1005, np.nan, 
                     "python-requests/2.21.0"],
                    ["97.105.15.120", "[18/Apr/2019:19:42:41+0000]", 
                     "GET /api/v1/sales?page=79/HTTP/1.1", 301, 2560, np.nan, 
                     "python-requests/2.21.0"],
                    ["97.105.19.58", "[19/Apr/2019:19:42:41+0000]", 
                     "GET /api/v1/sales?page=79/HTTP/1.1", 200, 2056327, np.nan, 
                     "python-requests/2.21.0"]], columns=colnames)

df = df_orig.append(new)

In [5]:
df.head(3)

,ip,timestamp,request_method,status,size,destination,request_agent
0,97.105.19.58,[16/Apr/2019:19:34:42 +0000],"""GET /api/v1/sales?page=81 HTTP/1.1""",200,512495,NaN,"""python-requests/2.21.0"""
1,97.105.19.58,[16/Apr/2019:19:34:42 +0000],"""GET /api/v1/items HTTP/1.1""",200,3561,NaN,"""python-requests/2.21.0"""
2,97.105.19.58,[16/Apr/2019:19:34:44 +0000],"""GET /api/v1/sales?page=82 HTTP/1.1""",200,510103,NaN,"""python-requests/2.21.0"""

In [ ]:
#unique values by column
type(df.ip.unique())

In [ ]:
# one off requests
df.groupby('request_method')['request_method'].count().sort_values().head(15)

In [9]:
# frequency of IPs
df_ip_unique = df.groupby('ip')['ip'].count().sort_values(ascending=False).tail(18)

In [10]:
df_ip_unique.index

Index(['68.201.219.223', '24.26.242.9', '52.87.230.102', '35.175.171.137',
       '70.121.214.34', '3.88.129.158', '3.92.201.136', '34.207.64.242',
       '34.229.70.250', '35.174.209.2', '95.31.18.119', '45.23.250.16',
       '95.31.16.121', '97.105.15.120', '52.91.30.150', '54.145.52.184',
       '54.172.14.223', '52.90.165.200'],
      dtype='object', name='ip')

In [ ]:
#52.87.230.102, 35.175.171.137 3.88.129.158, 3.92.201.136, 34.207.64.242 
# 34.229.70.250, 35.174.209.2, 52.91.30.150, 54.145.52.184
#coming from Virginia, Amazon.com

# 45.23.250.16 New Braunfels

#### 95.31.16.121 Moscow. HTTP 301 request to redirect URL

<img src="russia.png" alt="Drawing" style="width: 350px;"/>

In [13]:
df[df.ip == '95.31.16.121']

,ip,timestamp,request_method,status,size,destination,request_agent
1,95.31.16.121,[17/Apr/2019:19:36:41+0000],GET /api/v1/sales?page=79/HTTP/1.1,301,1005,NaN,python-requests/2.21.0

In [ ]:
source = urllib.request.urlopen('https://www.ip-tracker.org').read()
soup = bs.BeautifulSoup(source,'lxml')

In [11]:
ip_list = df.ip.unique())
table = soup.find_all("table",{"class":"table_dark_green"})

In [ ]:
ip_list
for i in ip_list_short:
    source = f'https://www.melissa.com/v2/lookups/iplocation/ip/?ip={i}&site='

In [ ]:
table = soup.find(id='tableInfo50')

In [ ]:
ip_list_short

In [ ]:
#rows = table.findChildren(['tr'])
ip_data = []

In [13]:
ip_data = []
for i in ip_list_short:
    source = f'https://www.melissa.com/v2/lookups/iplocation/ip/?ip={i}'
    soup = bs.BeautifulSoup(source,'lxml')
    table = soup.find(id='tableInfo50')
    rows = table.findChildren(['tr'])
    for row in rows:
        values = []
        cells = row.findChildren('td')
        for cell in cells:
            value = cell.string
            values.append(value)
        ip_data.append(values[1])
        #print(values[1])
        #country =
       # region = 

    #     isp = 
    #     lat =
    #     long =
    #     org =

    # for t in table:
    #     rating = t.select('span',{"class":"num"})
    #     name = t.select('a',{"class":"name"})
    #     brewery = t.select('a',{"class":"style"})

AttributeError: 'NoneType' object has no attribute 'findChildren'

In [48]:

source = 'https://www.melissa.com/v2/lookups/iplocation/ip/?ip=97.105.19.58&site='
soup = bs.BeautifulSoup(source,'lxml')
table = soup.find(id='content')
#rows = table.findChildren(['tr'])
p

None

In [36]:
soup.find_all('table')
print(soup)

<html><body><p>https://www.melissa.com/v2/lookups/iplocation/ip/?ip=3.92.201.136&amp;site=</p></body></html>

In [37]:
soup.find('')

In [6]:
df.describe()

             status          size
count  13978.000000  1.397800e+04
mean     200.356703  4.500019e+05
std       10.182001  1.614915e+05
min      200.000000  0.000000e+00
25%      200.000000  5.006370e+05
50%      200.000000  5.101380e+05
75%      200.000000  5.112910e+05
max      499.000000  2.056327e+06

In [8]:
df.dtypes

ip                object
timestamp         object
request_method    object
status             int64
size               int64
destination       object
request_agent     object
dtype: object

In [10]:
df.nunique()

ip                  22
timestamp         9957
request_method     220
status               3
size               191
destination         18
request_agent       10
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13978 entries, 0 to 3
Data columns (total 7 columns):
ip                13978 non-null object
timestamp         13978 non-null object
request_method    13978 non-null object
status            13978 non-null int64
size              13978 non-null int64
destination       25 non-null object
request_agent     13978 non-null object
dtypes: int64(2), object(5)
memory usage: 873.6+ KB

In [18]:
df

,ip,timestamp,request_method,status,size,destination,request_agent
0,97.105.19.58,[16/Apr/2019:19:34:42 +0000],"""GET /api/v1/sales?page=81 HTTP/1.1""",200,512495,NaN,"""python-requests/2.21.0"""
1,97.105.19.58,[16/Apr/2019:19:34:42 +0000],"""GET /api/v1/items HTTP/1.1""",200,3561,NaN,"""python-requests/2.21.0"""
2,97.105.19.58,[16/Apr/2019:19:34:44 +0000],"""GET /api/v1/sales?page=82 HTTP/1.1""",200,510103,NaN,"""python-requests/2.21.0"""
3,97.105.19.58,[16/Apr/2019:19:34:46 +0000],"""GET /api/v1/sales?page=83 HTTP/1.1""",200,510003,NaN,"""python-requests/2.21.0"""
4,97.105.19.58,[16/Apr/2019:19:34:48 +0000],"""GET /api/v1/sales?page=84 HTTP/1.1""",200,511963,NaN,"""python-requests/2.21.0"""
5,97.105.19.58,[16/Apr/2019:19:34:48 +0000],"""GET /api/v1/stores HTTP/1.1""",200,1328,NaN,"""python-requests/2.21.0"""
6,97.105.19.58,[16/Apr/2019:19:34:50 +0000],"""GET /api/v1/sales?page=85 HTTP/1.1""",200,510753,NaN,"""python-requests/2.21.0"""
7,97.105.19.58,[16/Apr/2019:19:34:52 +0000],"""GET /api/v1/sales?page=86 HTTP/1.1""",200,510348,NaN,"""python-requests/2.21.0"""
8,97.105.19.58,[16/Apr/2019:19:34:52 +0000],"""GET / HTTP/1.1""",200,42,NaN,"""python-requests/2.21.0"""
9,97.105.19.58,[16/Apr/2019:19:34:53 +0000],"""GET /api/v1/items HTTP/1.1""",200,3561,NaN,"""python-requests/2.21.0"""
10,97.105.19.58,[16/Apr/2019:19:34:53 +0000],"""GET /api/v1/items?page=2 HTTP/1.1""",200,3659,NaN,"""python-requests/2.21.0"""
11,97.105.19.58,[16/Apr/2019:19:34:53 +0000],"""GET /api/v1/items?page=3 HTTP/1.1""",200,1787,NaN,"""python-requests/2.21.0"""
12,97.105.19.58,[16/Apr/2019:19:34:54 +0000],"""GET /api/v1/sales HTTP/1.1""",200,493905,NaN,"""python-requests/2.21.0"""
13,97.105.19.58,[16/Apr/2019:19:34:54 +0000],"""GET /api/v1/sales?page=87 HTTP/1.1""",200,510540,NaN,"""python-requests/2.21.0"""
14,97.105.19.58,[16/Apr/2019:19:34:56 +0000],"""GET /api/v1/sales?page=88 HTTP/1.1""",200,512469,NaN,"""python-requests/2.21.0"""
15,97.105.19.58,[16/Apr/2019:19:34:58 +0000],"""GET /api/v1/sales?page=89 HTTP/1.1""",200,512044,NaN,"""python-requests/2.21.0"""
16,97.105.19.58,[16/Apr/2019:19:35:01 +0000],"""GET /api/v1/sales?page=90 HTTP/1.1""",200,510438,NaN,"""python-requests/2.21.0"""
17,97.105.19.58,[16/Apr/2019:19:35:03 +0000],"""GET /api/v1/sales?page=91 HTTP/1.1""",200,511883,NaN,"""python-requests/2.21.0"""
18,97.105.19.58,[16/Apr/2019:19:35:05 +0000],"""GET /api/v1/sales?page=92 HTTP/1.1""",200,512273,NaN,"""python-requests/2.21.0"""
19,97.105.19.58,[16/Apr/2019:19:35:07 +0000],"""GET /api/v1/sales?page=93 HTTP/1.1""",200,510147,NaN,"""python-requests/2.21.0"""
20,97.105.19.58,[16/Apr/2019:19:35:09 +0000],"""GET /api/v1/sales?page=94 HTTP/1.1""",200,510138,NaN,"""python-requests/2.21.0"""
21,97.105.19.58,[16/Apr/2019:19:35:10 +0000],"""GET /api/v1/sales?page=95 HTTP/1.1""",200,511966,NaN,"""python-requests/2.21.0"""
22,97.105.19.58,[16/Apr/2019:19:35:12 +0000],"""GET /api/v1/sales?page=96 HTTP/1.1""",200,510046,NaN,"""python-requests/2.21.0"""
23,97.105.19.58,[16/Apr/2019:19:35:14 +0000],"""GET /api/v1/sales?page=97 HTTP/1.1""",200,509783,NaN,"""python-requests/2.21.0"""
24,97.105.19.58,[16/Apr/2019:19:35:16 +0000],"""GET /api/v1/sales?page=98 HTTP/1.1""",200,509806,NaN,"""python-requests/2.21.0"""
25,97.105.19.58,[16/Apr/2019:19:35:18 +0000],"""GET /api/v1/sales?page=99 HTTP/1.1""",200,512312,NaN,"""python-requests/2.21.0"""
26,97.105.19.58,[16/Apr/2019:19:35:20 +0000],"""GET /api/v1/sales?page=100 HTTP/1.1""",200,512674,NaN,"""python-requests/2.21.0"""
27,97.105.19.58,[16/Apr/2019:19:35:22 +0000],"""GET /api/v1/sales?page=101 HTTP/1.1""",200,510509,NaN,"""python-requests/2.21.0"""
28,97.105.19.58,[16/Apr/2019:19:35:24 +0000],"""GET /api/v1/sales?page=102 HTTP/1.1""",200,512612,NaN,"""python-requests/2.21.0"""
29,97.105.19.58,[16/Apr/2019:19:35:26 +0000],"""GET /api/v1/sales?page=103 HTTP/1.1""",200,512764,NaN,"""python-requests/2.21.0"""
...,...,...,...,...,...,...,...
13948,97.105.19.58,[17/Apr/2019:12:54:50 +0000],"""GET /api/v1/sales?page=44 HTTP/1.1""",200,512701,NaN,"""python-requests/2.21.0"""
13949,97.105.19.58,[17/Apr/2019:12:54:51 +0000],"""GET /api/v1/sales?page=45 HTTP/1.1""",200,512241,NaN,"""python-requests/2.21.0"""
13950,97.105.19.58,[17/Apr/2019:12:54:53 +0000],"""GET /api/v1/sales?page=50 HTTP/1.1""",200,510139,NaN,"""python-requests/2.21.0"""
13951,97.105.19.58,[17/Apr/2019:12:54:54 +0000],"""GET /api/v1/sales?page=48 HTTP/1.1""",200,513027,NaN,"""python-requests/2.21.0"""
13952,97.105.19.58,[17/Apr/2019:12:54:54 +0000],"""GET /api/v1/sales?page=46 HTTP/1.1""",200,510810,NaN,"""python-requests/2.21.0"""
13953,97.105.19.58,[17/Apr/2019:12:54:55 +0000],"""GET /api/v1/sales?page=47 HTTP/1.1""",200,511454,NaN,"""python-requests/2.21.0"""
13954,97.105.19.58,[17/Apr/2019:12:54:57 +0000],"""GET /api/v1/sales?page=52 HTTP/1.1""",200,512589,NaN,"""python-requests/2.21.0"""
13955,97.105.19.58,[17/Apr/2019:12:54:58 +0000],"""GET /api/v1/sales?page=54 HTTP/1.1""",200,511118,NaN,"""python-requests/2.21.0"""
13956,97.105.19.58,[17/Apr/2019:12:54:59 +0000],"""GET /api/v1/sales?page=53 HTTP/1.1""",200,511577,NaN,"""python-requests/2.21.0"""
13957,97.105.19.58,[17/Apr/2019:12:54:59 +0000],"""GET /api/v1/sales?page=58 HTTP/1.1""",200,510020,NaN,"""python-requests/2.21.0"""
13958,97.105.19.58,[17/Apr/2019:12:55:00 +0000],"""GET /api/v1/sales?page=51 HTTP/1.1""",200,511530,NaN,"""python-requests/2.21.0"""
13959,97.105.19.58,[17/Apr/2019:12:55:01 +0000],"""GET /api/v1/sales?page=55 HTTP/1.1""",200,513736,NaN,"""python-requests/2.21.0"""
13960,97.105.19.58,[17/Apr/2019:12:55:03 +0000],"""GET /api/v1/sales?page=56 HTTP/1.1""",200,510120,NaN,"""python-requests/2.21.0"""
13961,97.105.19.58,[17/Apr/2019:12:55:03 +0000],"""GET /api/v1/sales?page=59 HTTP/1.1""",200,511959,NaN,"""python-requests/2.21.0"""
13962,97.105.19.58,[17/Apr/2019:12:55:04 +0000],"""GET /api/v1/sales?page=63 HTTP/1.1""",200,512205,NaN,"""python-requests/2.21.0"""
13963,97.105.19.58,[17/Apr/2019:12:55:06 +0000],"""GET /api/v1/sales?page=57 HTTP/1.1""",200,509933,NaN,"""python-requests/2.21.0"""
13964,97.105.19.58,[17/Apr/2019:12:55:06 +0000],"""GET /api/v1/sales?page=61 HTTP/1.1""",200,510084,NaN,"""python-requests/2.21.0"""
13965,97.105.19.58,[17/Apr/2019:12:55:08 +0000],"""GET /api/v1/sales?page=60 HTTP/1.1""",200,510123,NaN,"""python-requests/2.21.0"""
13966,97.105.19.58,[17/Apr/2019:12:55:09 +0000],"""GET /api/v1/sales?page=67 HTTP/1.1""",200,510139,NaN,"""python-requests/2.21.0"""
13967,97.105.19.58,[17/Apr/2019:12:55:09 +0000],"""GET /api/v1/sales?page=66 HTTP/1.1""",200,513313,NaN,"""python-requests/2.21.0"""
13968,97.105.19.58,[17/Apr/2019:12:55:09 +0000],"""GET /api/v1/sales?page=64 HTTP/1.1""",200,511251,NaN,"""python-requests/2.21.0"""
13969,97.105.19.58,[17/Apr/2019:12:55:12 +0000],"""GET /api/v1/sales?page=62 HTTP/1.1""",200,511544,NaN,"""python-requests/2.21.0"""
13970,97.105.19.58,[17/Apr/2019:12:55:12 +0000],"""GET /api/v1/sales?page=65 HTTP/1.1""",200,511201,NaN,"""python-requests/2.21.0"""
13971,97.105.19.58,[17/Apr/2019:12:55:13 +0000],"""GET /api/v1/sales?page=73 HTTP/1.1""",200,511781,NaN,"""python-requests/2.21.0"""
13972,97.105.19.58,[17/Apr/2019:12:55:13 +0000],"""GET /api/v1/sales?page=69 HTTP/1.1""",200,510136,NaN,"""python-requests/2.21.0"""
13973,97.105.19.58,[17/Apr/2019:12:55:14 +0000],"""GET /api/v1/sales?page=71 HTTP/1.1""",200,510166,NaN,"""python-requests/2.21.0"""
0,95.31.18.119,[21/Apr/2019:10:02:41+0000],GET /api/v1/items/HTTP/1.1,200,1153005,NaN,python-requests/2.21.0
1,95.31.16.121,[17/Apr/2019:19:36:41+0000],GET /api/v1/sales?page=79/HTTP/1.1,301,1005,NaN,python-requests/2.21.0
2,97.105.15.120,[18/Apr/2019:19:42:41+0000],GET /api/v1/sales?page=79/HTTP/1.1,301,2560,NaN,python-requests/2.21.0
3,97.105.19.58,[19/Apr/2019:19:42:41+0000],GET /api/v1/sales?page=79/HTTP/1.1,200,2056327,NaN,python-requests/2.21.0